INSERT INTO marvel_comics.WEB_MULTILENGUAJE_LABELS
(`KEY`, VALUE, LENGUAGE, APPLICATION)
VALUES('comics.iphone.onboard.1','Title 1','ES','MARVEL_COMICS_PRAGMA');

INSERT INTO marvel_comics.WEB_MULTILENGUAJE_LABELS
(`KEY`, VALUE, LENGUAGE, APPLICATION)
VALUES('comics.iphone.onboard.2','Title 2','ES','MARVEL_COMICS_PRAGMA');

INSERT INTO marvel_comics.WEB_MULTILENGUAJE_LABELS
(`KEY`, VALUE, LENGUAGE, APPLICATION)
VALUES('comics.iphone.onboard.3','Title 3','ES','MARVEL_COMICS_PRAGMA');

INSERT INTO marvel_comics.WEB_MULTILENGUAJE_LABELS
(`KEY`, VALUE, LENGUAGE, APPLICATION)
VALUES('comics.iphone.onboard.description.1','Description 1','ES','MARVEL_COMICS_PRAGMA');

INSERT INTO marvel_comics.WEB_MULTILENGUAJE_LABELS
(`KEY`, VALUE, LENGUAGE, APPLICATION)
VALUES('comics.iphone.onboard.description.2','Description 2','ES','MARVEL_COMICS_PRAGMA');

INSERT INTO marvel_comics.WEB_MULTILENGUAJE_LABELS
(`KEY`, VALUE, LENGUAGE, APPLICATION)
VALUES('comics.iphone.onboard.description.3','Description 3','ES','MARVEL_COMICS_PRAGMA');
